// Class automatically generated by Dev-C++ New Class wizard

#include "simclock.h" // class's header file

// class constructor
simClock::simClock()
{
	nowTime=0.0; 
}

// class destructor
simClock::~simClock()
{
	// insert your code here
}
