// Class automatically generated by Dev-C++ New Class wizard

#include <iostream>
#include <vector>

#include "simobject.h"
#include "simmachine.h"
#include "simevent.h"
#include "simpart.h"
#include "simqueue.h"
#include "simclock.h"



#ifndef SIMEVENTLIST_H
#define SIMEVENTLIST_H

#define EVENT_MAX 100 
//100个事件

/*
 * 事件表类
 */
class simEventList
{
	public:
        //vector<int> theList; 
        simEvent* theList[EVENT_MAX];//100个事件
        int nowEventNum; 
        bool AddEvent(simEvent* pEvt); 
        simEvent* theFirstEvent(); 
        bool notifyObjects(); 
        bool happenFirst(); 
		// class constructor
		simEventList();
		// class destructor
		~simEventList();
};

#endif // SIMEVENTLIST_H
