// Class automatically generated by Dev-C++ New Class wizard
#include "simobject.h"
#include "simevent.h" // class's header file
#include "simpart.h"
#include "simqueue.h"
#include "simclock.h"

#include "simmodel.h"
extern simModel theModel;

// class constructor
simEvent::simEvent()
{
	// insert your code here
}

// class destructor
simEvent::~simEvent()
{
	// insert your code here
}

bool simEvent::happen()
{
   
/* TODO (#1#): 事件发生时的处理 */
    theModel.theClock.nowTime=happenTime;
    printf("\nNOW TIME=%f\n",happenTime); 
    theObj->response(theType);
    return true; 

} 
