// Class automatically generated by Dev-C++ New Class wizard


#include <iostream>
#include "simobject.h"
#include "simmachine.h"
#include "simevent.h"
#include "simpart.h"
#include "simqueue.h"
#include "simclock.h" 
#include "simobjectlist.h"
#include "simeventlist.h"

#include "simmodel.h" // class's header file

// class constructor
simModel::simModel()
{
	// insert your code here
}

// class destructor
simModel::~simModel()
{
	// insert your code here
}

bool simModel::run()
{
    //产生初始事件
    //int k=0; 
    printf("\n\nTIME=%f\nchecking....\n",theClock.nowTime);
    for(int k=0;k<theObjectList.TotalObject;k++)
    {
        simObject* pS=theObjectList.theList[k]; 
        if(MACHINE_TYPE==pS->theObjectType){
            printf("....k=%d..now is Machine[%d]....",k,pS->InstanceNum); 
            simMachine* pM=(simMachine* )theObjectList.theList[k];
            pM->check(); 
        }
        else{
            printf("....k=%d...is a QUEUE %d\n",k,pS->InstanceNum); 
        } 
    } 
    //开始循环检索事件表
    do{
        theEventList.happenFirst();
        //printf("\n\nTIME=%f\n",theClock.nowTime); 
    }
    while(theEventList.nowEventNum>0); 
    printf("The EVENT TABLE is Empty, Simulation End\n\n"); 
    return true; 
    
} 
bool simModel::reset()
{
    
    
} 
bool simModel::stop()
{
    
} 

