// Class automatically generated by Dev-C++ New Class wizard

#include "simobject.h" // class's header file
#include "simevent.h"
// class constructor
simObject::simObject()
{
	// insert your code here
}

// class destructor
simObject::~simObject()
{
	// insert your code here
}
