// Class automatically generated by Dev-C++ New Class wizard
#include <iostream>
#include "simobject.h"
#include "simmachine.h"
#include "simevent.h"
#include "simpart.h"
#include "simqueue.h"
#include "simclock.h"


#ifndef SIMOBJECTLIST_H
#define SIMOBJECTLIST_H


#define MAX_OBJECT_NUM 200  //最多两百个元素 

/*
 * 元素表类
 */
class simObjectList
{
	public:
        simObject* theList[MAX_OBJECT_NUM];
        int TotalObject; 
		// class constructor
		simObjectList();
		// class destructor
		~simObjectList();
		
		bool AddSimObject(simObject* asimObj); 
};

#endif // SIMOBJECTLIST_H
