// Class automatically generated by Dev-C++ New Class wizard
#include "global.h"
#include "simpart.h" // class's header file

// class constructor
simPart::simPart()
{
	// insert your code here
	//for(int i=0;i<=WORKSTATION_NUM;i++)
    //{ 
    //    PartType[i]=UNKNOWN_TYPE; 
    //	ToBePartType[i]=UNKNOWN_TYPE;
    //} 
    PartType=UNKNOWN_TYPE;
    ToBePartType=UNKNOWN_TYPE;
    Priority=UNKNOWN_PRIORITY;
}

// class destructor
simPart::~simPart()
{
	// insert your code here
}

 
simPart::simPart(int theType)
{
    
//    for(int i=0;i<=WORKSTATION_NUM;i++)
//    {
//        PartType[i]=UNKNOWN_TYPE;
//    	ToBePartType[i]=UNKNOWN_TYPE;
//    }
    PartType=theType;
    Priority=UNKNOWN_PRIORITY;
}

simPart::simPart(int theType,int thePry)
{
    
//    for(int i=0;i<=WORKSTATION_NUM;i++)
//    {
//        PartType[i]=UNKNOWN_TYPE;
//    	ToBePartType[i]=UNKNOWN_TYPE;
//    }
    PartType=theType;
    Priority=thePry;
}
 
bool simPart::setType(int theType)
{
    PartType=theType;
}
bool simPart::setTargetType(int aType)
{
    ToBePartType=aType; 
}		
bool simPart::setPriority(int p)
{
    Priority=p;
}		
