// Class automatically generated by Dev-C++ New Class wizard

#ifndef SIMPART_H
#define SIMPART_H

#include "global.h"


#define UNKNOWN_TYPE 99
#define UNKNOWN_PRIORITY 99


//5个工位 
/*
 * 纯零件类
 * 包括 类型、优先级、
 */
class simPart
{
	public:
        int PartType;//[WORKSTATION_NUM+1];//当前类型号 
        int ToBePartType;//[WORKSTATION_NUM+1];//计划将要生成的类型 
        int Priority; 
		// class constructor
		simPart();
		simPart(int theType);
		simPart(int theType,int thePry);
		// class destructor
		bool setType(int theType);//,int thePry);
		bool setTargetType(int aType); 
		bool setPriority(int p);
		~simPart();
};

#endif // SIMPART_H
