// Class automatically generated by Dev-C++ New Class wizard

#ifndef SIMCLOCK_H
#define SIMCLOCK_H

/*
 * ∑¬’Ê÷”
 */
class simClock
{
	public:
        double nowTime; 
		// class constructor
		simClock();
		// class destructor
		~simClock();
};

#endif // SIMCLOCK_H
