// Class automatically generated by Dev-C++ New Class wizard

#include <iostream>
#include "simobject.h"
#include "simmachine.h" 
#include "simevent.h"
#include "simpart.h"
#include "simqueue.h"
#include "simclock.h" 
#include "simobjectlist.h"
#include "simeventlist.h"
#ifndef SIMMODEL_H
#define SIMMODEL_H

/*
 * 一个完整的仿真模型类
 */
class simModel
{
	public:
        simObjectList theObjectList;
        simEventList theEventList;
        simClock theClock;
         
		// class constructor
		simModel();
		// class destructor
		~simModel();
		bool run();
        bool reset();
        bool stop();
        //bool  
};

#endif // SIMMODEL_H
