// Class automatically generated by Dev-C++ New Class wizard

#include "simpart.h" // class's header file

// class constructor
simPart::simPart()
{
	// insert your code here
	for(int i=0;i<=WORKSTATION_NUM;i++)
    { 
        PartType[i]=UNKNOWN_TYPE; 
    	ToBePartType[i]=UNKNOWN_TYPE;
    } 
}

// class destructor
simPart::~simPart()
{
	// insert your code here
}

 
simPart::simPart(int theType)
{
    
    for(int i=0;i<=WORKSTATION_NUM;i++)
    {
        PartType[i]=UNKNOWN_TYPE;
    	ToBePartType[i]=UNKNOWN_TYPE;
    }
    PartType[0]=theType;
    Priority=999;
}

simPart::simPart(int theType,int thePry)
{
    
    for(int i=0;i<=WORKSTATION_NUM;i++)
    {
        PartType[i]=UNKNOWN_TYPE;
    	ToBePartType[i]=UNKNOWN_TYPE;
    }
    PartType[0]=theType;
    Priority=thePry;
}
 
		
		
