// Class automatically generated by Dev-C++ New Class wizard
#include "simpart.h" 

#ifndef SIMQUEUE_H
#define SIMQUEUE_H

#include "simobject.h" // inheriting class's header file

#define PULL_TYPE 1
//1-先到先抽取，传统型
//2-优化抽取 

#define QUEUE_LENGTH_MAX 50 

/*
 * 队列/缓冲区类
 */
class simQueue : public simObject
{
	public:
		// class constructor
		int Capacity;//容量
        simPart *content[QUEUE_LENGTH_MAX];
        int nowIn; 
		simQueue();
		simQueue(int Capa);
		// class destructor
		~simQueue();
		simPart *GivePart();
        bool GetPart(simPart *aPart); 
		bool canIn();
		bool canOut();
};

#endif // SIMQUEUE_H
